/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.Scanner;

public class App {
    Scanner scan = new Scanner(System.in);
    String playerName;
    String playerWeapon;
    String potion = "Heath Potion";
    int playerHP;
    int goblinHP;
    int choice;
    int playerCoin;
    int innkeeperCoin;
    int legendaryRing;

    public static void main(String[] args) {

        App app;
        // With this you can choose what method you will call first or in what order!
        app = new App();
        app.displayCharacterInfo();
        app.playerInfo();
    }

    public void info() {

    }

    public void displayCharacterInfo() {
        playerHP = 50;
        playerCoin = 50;
        playerWeapon = "Knife";
        innkeeperCoin = 50;
        System.out.println("\n----------------------------------------------------------------");
        System.out.println("Welcome adventurer to this world please choose a name: ");
        playerName = scan.nextLine();
        System.out.println();

        System.out.println("Player stats:");

        System.out.println("Player Name: " + playerName + "\nPlayer current health " + playerHP
                + "\nPlayer current coin: " + playerCoin
                + "\nPlayer current weapon: " + playerWeapon);
    }

    public void playerInfo() {

        System.out.println(
                "\nYou are located in Inn, in the letter that u received form your brother say that, there is a rumor, that there is one ring that it has Legendary Power, and you need to find it!\n");
        System.out.println(
                playerName
                        + ": Hmmm.... Maybe I should ask Innkeeper if he heard anything about the legendary ring.\n");
        System.out.println("Press 1 to proceed ");
        choice = scan.nextInt();
        if (choice == 1) {
            inn();
        } else {
            playerInfo();
        }

    }

    public void inn() {
        System.out.println("\n----------------------------------------------------------------");
        System.out.println("You go to the Innkeeper\n");
        System.out.println("----------------------------------------------------------------\n");
        System.out.println("Innkeeper: Greetings stranger how can I help you today?\n");
        System.out.println("1. Can I ask you question about legendary ring?");
        System.out.println("2. Can I buy something from you?");
        System.out.println("3. Leave");
        System.out.println("----------------------------------------------------------------\n");

        choice = scan.nextInt();
        System.out.println("\n----------------------------------------------------------------");
        if (choice == 1) {
            System.out.println(
                    "Sure! So you also heard about that rumor, lets not say out laud! It located in the crossroad on right road that leads to big forest");
            System.out.println(playerName + ": Ah I see thank you!");
            inn();
            System.out.println("----------------------------------------------------------------");
        }
        if (choice == 2) {
            System.out.println("Sure, I have [health potion], [bread] or [wine]!");
            System.out.println("Innkeeper has " + innkeeperCoin);

            System.out.println("1. Health Potion (It can heal you for 5 health.)");
            System.out.println("Health Potion cost 10 coin;");

            System.out.println("2. Bread (That can heal you for 1 health.)");
            System.out.println("Health Potion cost 10 coin;");

            System.out.println("3. Wine (It can heal you for 2 health)");
            System.out.println("Health Potion cost 10 coin;");

            System.out.println("4. Leave");
            choice = scan.nextInt();

            if (choice == 1) {
                innkeeperCoin = playerCoin + 10;
                System.out.println("\nThank you for buying " + potion + "!");
                System.out.println("Your current balance: " + playerCoin);
                inn();
            } else if (choice == 2) {
            } else if (choice == 3) {
            } else if (choice == 4) {
            } else {
                inn();
            }

        }

    }
}
